[package]
name = "setAndRenew"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]

# For remote import, use the `{ git = "...", subdir = "...", rev = "..." }`.
# Revision can be a branch, a tag, and a commit hash.
WAL = { git = "https://github.com/MystenLabs/walrus.git",   rev = "main", subdir = "testnet-contracts/wal"}
Walrus = { git = "https://github.com/MystenLabs/walrus.git",   rev = "main", subdir = "testnet-contracts/walrus"}

# For local dependencies use `local = path`. Path is relative to the package root
# Local = { local = "../path/to" }

# To resolve a version conflict and force a specific version for dependency
# override use `override = true`
# Override = { local = "../conflicting/version", override = true }


[addresses]

warlot = "0x0"
# warlotpackage    = "0x90a4dbfcfb4762416a81436e54fbf3ebba1cd5729c06705ed10ea66da547d704"
# Named addresses will be accessible in Move as `@name`. They're also exported:
# for example, `std = "0x1"` is exported by the Standard Library.
# alice = "0xA11CE"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# warlotpackage = "0x90a4dbfcfb4762416a81436e54fbf3ebba1cd5729c06705ed10ea66da547d704"
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"


# [build]
# override_addresses = true